### ISSUE TITLE
Array of VL53L0X Objects

### ISSUE THREAD

**Issue by skipper762** [stm32duino/VL53L0X#9]
Hi,

I'm trying to create an array of these sensors that can be scaled in size, however with my current code the `InitSensor` method is always failing. 

The array is created here
```
 #define NUM_SENSORS 3   
#define WIRE_INTERFACE Wire  
int XHUT_PINS[NUM_SENSORS]={33,35, 37};   
int GPIO_PINS[NUM_SENSORS]={34,36, 38};   
byte I2C_addresses[NUM_SENSORS] = {0x10,0x11, 0x12};   
VL53L0X* range_sensor_aray[NUM_SENSORS]; 
```
Then initialised here 
```
for(int i=0;i<NUM_SENSORS;i++){
    range_sensor_aray[i] = new VL53L0X(&WIRE_INTERFACE ,XHUT_PINS[i],GPIO_PINS[i]);
    range_sensor_aray[i]->VL53L0X_Off(); 
  }

  for(int i=0;i<NUM_SENSORS;i++){
    status = range_sensor_aray[i]->InitSensor(I2C_addresses[i]); 
    #ifdef DEBUG 
      if(status) DEBUG_SERIAL.println("Init of Sensor " + String(i) + " Failed"); 
    #endif  
    range_sensor_aray[i]->VL53L0X_Off();  
  }

  for(int i=0;i<NUM_SENSORS;i++){
     range_sensor_aray[i]->VL53L0X_On(); 
    
  }
```

I'm not sure if it's my code, or the class its self that is causing this issue.

**Comment by cparata** [comment]
Hi,
which MCU board are you using with the VL53L0X components? The VL53L0X class requires a lot of stack resources and I experienced issues to control more than one VL53L0X component with for example an Arduino UNO or an Arduino Nano. I did not have any issue instead with more powerful boards like Arduino DUE or ST Nucleo boards. The code should be okay even if you can simply write:

for(int i=0;i<NUM_SENSORS;i++){
    range_sensor_aray[i] = new VL53L0X(&WIRE_INTERFACE ,XHUT_PINS[i],GPIO_PINS[i]);
    range_sensor_aray[i]->VL53L0X_Off(); 
  }

  for(int i=0;i<NUM_SENSORS;i++){
    status = range_sensor_aray[i]->InitSensor(I2C_addresses[i]); 
    #ifdef DEBUG 
      if(status) DEBUG_SERIAL.println("Init of Sensor " + String(i) + " Failed"); 
    #endif   
  }

Please, check also that all wire connections among the MCU board and the several VL53L0X components are done correctly.
Best Regards,
Carlo

**Comment by skipper762** [comment]
Hi Carlo,

I've tried running this on a teensy 3.6, 3.5 and a Due.
I'll try your slightly tweaked code now,

Cheers,
Nick

**Comment by cparata** [comment]
Hi Nick,
did you solve your issue?
Regards,
Carlo

**Comment by fpistm** [comment]
Hi @skipper762,
any feedback?

**Comment by method-nick** [comment]
@fpistm 
Hi 

Sorry for the lack of response: 
I ended up just creating individual instances of not using the array method. 
It made the code considerably messier, but it worked. 

This was only for a proof of concept so the test ring is now disassembled and we are now using a pure c implementation

**Comment by fpistm** [comment]
@method-nick 
No worries ;)
Thanks for the feedback and happy your proof of concept was OK.
So is this issue could be close?

**Comment by method-nick** [comment]
I'm not sure what you want to do with this issue as I did not resolve the problem of using these sensors in arrays.

**Comment by fpistm** [comment]
Ok let's it open.
Hope @cparata could check this.

**Comment by cparata** [comment]
Hi all,
finally I was able to test it and to understand the issue. Basically the initial code is wrong because if you perform  VL53L0X_Off after InitSensor, you reset the state machine of the sensor and you loose the settings of InitSensor API
[sketch_feedback.zip](https://github.com/stm32duino/VL53L0X/files/2644795/sketch_feedback.zip)

. So the correct code should be:

#define NUM_SENSORS 3   
#define WIRE_INTERFACE Wire  
int XHUT_PINS[NUM_SENSORS]={33,35, 37};   
int GPIO_PINS[NUM_SENSORS]={34,36, 38};   
byte I2C_addresses[NUM_SENSORS] = {0x10,0x11, 0x12};   
VL53L0X* range_sensor_aray[NUM_SENSORS]; 

Then initialised here

for(int i=0;i<NUM_SENSORS;i++){
    range_sensor_aray[i] = new VL53L0X(&WIRE_INTERFACE ,XHUT_PINS[i],GPIO_PINS[i]);
    range_sensor_aray[i]->VL53L0X_Off(); 
  }

  for(int i=0;i<NUM_SENSORS;i++){
    status = range_sensor_aray[i]->InitSensor(I2C_addresses[i]); 
    #ifdef DEBUG 
      if(status) DEBUG_SERIAL.println("Init of Sensor " + String(i) + " Failed"); 
    #endif  
  }

and it works perfectly on my side with Nucleo-F401RE and X-NUCLEO-53L0A1 (please give a look at the attached sketch).
We can close this issue. 
Best Regards,
Carlo
